const SKETCH_LINE_WIDTH = 3;

const QUOTES = [
  "Creativity takes courage.",
  "Simplicity is the soul of efficiency.",
  "Code is like humor. When you have to explain it, it is bad.",
  "Experience is the name everyone gives to their mistakes.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "Any fool can write code that a computer can understand. Good programmers write code humans can understand.",
  "First, solve the problem. Then, write the code.",
  "In order to be irreplaceable, one must always be different.",
  "Java is to JavaScript what car is to carpet.",
  "Sometimes, it's better to leave something alone, to pause, and that's very true of programming.",
  "Knowledge is power.",
  "Premature optimization is the root of all evil.",
  "Before software can be reusable it first has to be usable.",
  "Make it work, make it right, make it fast.",
  "The best error message is the one that never shows up.",
  "Learning never exhausts the mind.",
  "Code never lies, comments sometimes do.",
  "Fix the cause, not the symptom.",
  "The cleaner the code, the less the bugs.",
  "Computers are fast; programmers keep it slow.",
  "Talk is cheap. Show me the code.",
  "Beware of bugs in the above code; I have only proved it correct, not tried it.",
  "The function of good software is to make the complex appear simple.",
  "Testing leads to failure, and failure leads to understanding.",
  "If at first you don’t succeed; call it version 1.0.",
  "Simplicity is prerequisite for reliability.",
  "Walking on water and developing software from a specification are easy if both are frozen.",
  "The only way to learn a new programming language is by writing programs in it.",
  "A user interface is like a joke. If you have to explain it, it’s not that good.",
  "One man’s crappy software is another man’s full-time job.",
  "Deleted code is debugged code.",
  "The computer was born to solve problems that did not exist before.",
  "Quality is not an act, it is a habit.",
  "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
  "Controlling complexity is the essence of computer programming.",
  "Innovation distinguishes between a leader and a follower.",
  "Code is like a poem; it has to sound good, not only to work.",
  "Good code is its own best documentation.",
  "Imagination is more important than knowledge.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Stay hungry, stay foolish.",
  "The secret of getting ahead is getting started.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "It always seems impossible until it’s done.",
  "Whether you think you can or you think you can’t, you’re right.",
  "The best way to predict the future is to invent it.",
  "Sometimes, no solution is part of the solution.",
  "Your code is like a joke; it only works if someone else gets it.",
  "The only thing worse than a bug is an undiscovered one.",
  "Opportunities don't happen. You create them.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Dream big and dare to fail.",
  "Every accomplishment starts with the decision to try.",
  "Don't watch the clock; do what it does. Keep going.",
  "Happiness is a warm keyboard.",
  "If opportunity doesn’t knock, build a door.",
  "Never trust a computer you can’t throw out a window.",
  "The more you code, the more you know what to code.",
  "If you think adventure is dangerous, try routine; it is lethal.",
  "Do one thing every day that scares you.",
  "Errors exist to prove that we try.",
  "Screw it, let's do it.",
  "Talent wins games, but teamwork wins championships.",
  "The mind is everything. What you think you become.",
  "Sometimes the smallest step in the right direction ends up being the biggest step.",
  "Why do Java developers wear glasses? Because they don't see sharp.",
  "A good programmer is someone who always looks both ways before crossing a one-way street.",
  "It's not a bug; it's an undocumented feature.",
  "You miss 100% of the shots you don't take.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Little by little, one travels far.",
  "Strive not to be a success, but rather to be of value.",
  "There is no place like 127.0.0.1.",
  "Without requirements or design, programming is the art of adding bugs to an empty text file.",
  "Every great developer you know got there by solving problems they were unqualified to solve.",
  "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.",
  "Programming isn't about what you know; it's about what you can figure out.",
  "If you torture the data long enough, it will confess to anything.",
  "Sometimes the questions are complicated and the answers are simple.",
  "Algorithms are opinions embedded in code.",
  "Satisfaction lies in the effort, not in the attainment.",
  "When in doubt, delete half the code.",
  "Everything is figureoutable.",
  "Life is short. Live it. Love is rare. Grab it.",
  "Great things are done by a series of small things brought together.",
  "When nothing goes right, go left.",
  "Dreams don’t work unless you do.",
  "Bugs are features with seniority.",
  "There are two ways to write error-free programs; only the third one works.",
  "Think twice, code once.",
  "Risk more than others think is safe.",
  "The future depends on what we do in the present.",
  "In coding as in life, the simplest answer is often correct.",
  "Perfection is not attainable, but if we chase perfection we can catch excellence.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "Even the smallest person can change the course of the future.",
  "Ideas are easy. Implementation is hard.",
  "There is no elevator to success; you have to take the stairs.",
  "Do what you can, with what you have, where you are."
];

const QUOTE_FADE_MS = 300;
